name: Build and Release
on: [push, pull_request]

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run make
      - name: Get Release ID
        id: get_release_id
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "v1.0.0"
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          asset_path: ./out/make/squirrel.windows/x64/
          asset_name: shutdown-timer-1.0.0 Setup.exe
          asset_content_type: application/octet-stream
          upload_url: ${{ steps.get_release_id.outputs.upload_url }}
          token: ${{ secrets.GITHUB_TOKEN }}